version: '3.9'

services:
  db:
    image: postgres:17.0
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres_emfa:/var/lib/postgresql/data
      - ./init_emfa.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=cost#123$
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mfa
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    hostname: localhost
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - ~/apps/kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "mfa_notification:3:1"